// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Categorizes a business listing based on its description.
 *
 * - categorizeBusinessListing - A function that categorizes a business listing.
 * - CategorizeBusinessListingInput - The input type for the categorizeBusinessListing function.
 * - CategorizeBusinessListingOutput - The return type for the categorizeBusinessListing function.
 */

import {ai} from '@/ai/genkit';
import {gemini25Flash} from '@genkit-ai/googleai';
import {z} from 'genkit';

const CategorizeBusinessListingInputSchema = z.object({
  description: z.string().describe('The description of the business listing.'),
});

export type CategorizeBusinessListingInput = z.infer<
  typeof CategorizeBusinessListingInputSchema
>;

const CategorizeBusinessListingOutputSchema = z.object({
  category: z
    .string()
    .describe(
      'The most relevant category for the business listing based on its description.'
    ),
});

export type CategorizeBusinessListingOutput = z.infer<
  typeof CategorizeBusinessListingOutputSchema
>;

export async function categorizeBusinessListing(
  input: CategorizeBusinessListingInput
): Promise<CategorizeBusinessListingOutput> {
  return categorizeBusinessListingFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeBusinessListingPrompt',
  input: {schema: CategorizeBusinessListingInputSchema},
  output: {schema: CategorizeBusinessListingOutputSchema},
  model: gemini25Flash,
  prompt: `You are an expert in business categorization. Based on the provided description, determine the most relevant category for the business listing.

Description: {{{description}}}

Category:`, // Removed example categories
});

const categorizeBusinessListingFlow = ai.defineFlow(
  {
    name: 'categorizeBusinessListingFlow',
    inputSchema: CategorizeBusinessListingInputSchema,
    outputSchema: CategorizeBusinessListingOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
